name: "Run Xanitizer Security Analysis"

on:
  # Run the workflow on each push
  # push:
  # Run the workflow each day at 5 am
  # schedule:
  #   - cron: '0 5 * * *'
  # Run the workflow manually
  workflow_dispatch:

jobs:
  run-xanitizer-security-analysis:
    # Xanitizer runs on ubuntu-latest and windows-latest.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
    - uses: actions/checkout@v2

    # Compile project (like mvn compile) and install all dependencies (like npm install)
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
      # Compile the code for Java projects and get all libraries, e.g. via Maven
    - run: mvn -B compile
    
      # Run the security analysis with a configuration file
    - name: Xanitizer Security Analysis
      id: xanitizer
      #uses: RIGS-IT/xanitizer-action@v1
      uses: RIGS-IT/xanitizer-action@master
      with:
        license: ${{ secrets.XANITIZER_LICENSE }}

      # Use the output from the `xanitizer` step
    - run: echo "Status messages from Xanitizer's security analysis - ${{ steps.xanitizer.outputs.security_analysis }}"
    
      # Archiving
    - uses: actions/upload-artifact@v2
      with:
        name: Xanitizer-Reports
        path: | 
          *.pdf
          *.sarif

      # Uploads results.sarif to GitHub using the upload-sarif action
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: Xanitizer-Findings-List.sarif
